### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sec13b** [Amunius/EppLPE#1]
![image](https://github.com/user-attachments/assets/9a1cf196-b1f8-412e-858b-889210f24f59)

**Comment by Amunius** [comment]
Hey @sec13b,
The 2 error code means that the system can not find the specified file. In this case it means that the Epp device probably hasn't been created or Epp.sys hasn't been loaded. This exploit assumes that Epp.sys has already been loaded in system. You can read more about this exploit on my blog: https://amunius.github.io/posts/Exploiting-kernel-heap-buffer-overflow/
By the way, remember that this exploit works only on vulnerable version of Epp.sys driver because this vulnerability has been fixed in newest version of this driver. You can load the driver by yourself, I have added the vulnerable driver file to repository: https://github.com/Amunius/EppLPE/blob/main/Driver/epp.sys
Have a nice day :)

**Comment by sec13b** [comment]
i read your blog , but i dont understand how  Epp.sys load.
the  user  i use has no rights 

sc.exe create epp.sys binPath= C:\windows\temp\epp.sys type= kernel && sc.exe start epp.sys

sc.exe create epp.sys binPath= C:\temp\epp.sys type= kernel && sc.exe start epp.sys

i put both in same folder \temp\

**Comment by Amunius** [comment]
Hey @sec13b,
I tried this way to load the driver and it seems that if this driver was loaded this way, it doesn't create Epp device object. I'm not sure why it is done this way. In order to understand why it doesn't work so, I would need to reverse engineer this driver in more details, but because of lack of free time I'm not planning to do so. However I have found another way to load that driver, maybe it's not the best way but it works. In order to do so you should install Emsisoft Anti-Malware Home, after it install the latest version of the driver, you can shut down the anti-malware. It makes it will unload the driver, and then you can replace the driver with vulnerable one, it is by default at this path: "C:\Program Files\Emsisoft Anti-Malware\epp.sys". Then after you start Emsisoft Anti-Malware, it will load the vulnerable driver. While doing so, I recommend you to disable internet connection so Emsisoft won't update the driver by itself. So basically to load this driver, there is need to found out the way how Emsisoft Anti-Malware loads the driver, but as I said I'm not planning to dig into it. I know this is not the best way to load the driver, but if you just want to analyse the expliot, it should be sufficient. Of course after loading the vulnerable driver, the exploit works well.
Have a great day :)

![Screenshot 2024-11-21 214548](https://github.com/user-attachments/assets/d5913036-27c4-420e-8382-1ac827ff1098)
